[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https://metamindworks.com;media-src https://metamindworks.com;style-src https://metamindworks.com;img-src *;frame-src 'none';script-src https://netlify-rum.netlify.app https://metamindworks.com"
